import { Inter } from "next/font/google";  // Importing the Inter font from Google Fonts
import "./globals.css";  // Import global styles
import { ClerkProvider } from "@clerk/nextjs";  // Import ClerkProvider for user management
const inter = Inter({ subsets: ["latin"] });  // Initialize the Inter font with Latin subset

// Enhanced metadata for the application
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "Next.js, React, Clerk, Web Development",  // Added keywords for SEO
  author: "Your Name",  // Added author for SEO
};

// RootLayout component that wraps the entire application
export default function RootLayout({ children }) {
  return (
    <ClerkProvider> {/* Provides Clerk services throughout the app */}
      <html lang="en"> {/* Sets the language of the document to English */}
        <body className={inter.className}>{children}</body> {/* Applies the Inter font class to the body */}
      </html>
    </ClerkProvider>
  );
}

// Consider adding an error boundary component here if needed
